import mongoose from "mongoose";

//Specifying schema for User Collection
/*
In MongoDB, instead of "tables" like in SQL, 
data is stored in "collections", which are groups of JSON documents. 
*/
const userSchema = new mongoose.Schema(
  {
    email: {
      type: String,
      required: true,
      unique: true,
    },
    fullName: {
      type: String,
      required: true,
    },
    password: {
      type: String,
      required: true,
      minlength: 6,
    },
    profilePic: {
      type: String,
      default: "",
    },
  },
  //_id it is a field which is autogenerated for every entry by mongoDB
  //for created at and updated at (for features like member since)
  { timestamps: true }
);

const User = mongoose.model("User", userSchema);

//export the user model so thst we can use this multiple files
export default User;
